[package]
name = "ethcontract"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "common",
  "derive",
]

[dependencies]
ethcontract-common = { path = "./common" }
ethcontract-derive = { path = "./derive" }
ethabi = "8.0"
ethsign = "0.7"
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
jsonrpc-core = "11.0"
lazy_static = "1.4"
rlp = "0.4"
serde_json = "1.0"
thiserror = "1.0"
tiny-keccak = "1.5"
web3 = "0.8"