[package]
name = "ethcontract"
version = "0.1.0"
authors = ["Nicholas Rodrigues Lordello <nlordell@gmail.com>"]
edition = "2018"

[workspace]
members = [
  "common",
  "derive",
]

[dependencies]
ethcontract-common = { path = "./common" }
ethcontract-derive = { path = "./derive" }
